---
Name: surveys
After:
  - 'framework/*'
  - 'cms/*'
---



SiteConfig:
  extensions:
    - SurveySiteConfigExtension



Director:
  rules:
    's/$SurveyID': 'SurveyController'



SurveyResponse:
  extensions:
    - JsonFieldExtension


SurveyController:
  extensions:
    - JsonApiExtension
