---
Name: surveys
After:
  - 'framework/*'
  - 'cms/*'
---



SiteConfig:
  extensions:
    - SurveySiteConfigExtension



Director:
  rules:
    's/$Survey': 'SurveyController'



SurveyResponse:
  extensions:
    - JsonFieldExtension
