---
Name: surveys
After:
  - 'framework/*'
  - 'cms/*'
---



SiteConfig:
  extensions:
    - SurveySiteConfigExtension



Director:
  rules:
    'survey/$SurveyID': 'SurveyApiController'



SurveyResponse:
  extensions:
    - JsonFieldExtension


SurveyApiController:
  extensions:
    - JsonApiExtension
    - ApiAuthExtension
