---
Name: surveys
After:
  - 'framework/*'
  - 'cms/*'
---



SiteConfig:
  extensions:
    - SurveySiteConfigExtension

Filesystem:
  sync_blacklisted_patterns:
    - '/^surveymedia$/i'



Director:
  rules:
    'api/survey/$SurveyID': 'SurveyApiController'
