---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
  - 'surveys/*'
---


# Set the default theme
SSViewer:
  theme: 'strapped'


# Custom configuration for PHP Classes
Page:
  extensions:
    - PageSidebarExtension

Page_Controller:
  extensions:
    - PageControllerSidebarExtension
