---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
  - 'surveys/*'
---


# Set the default theme
SSViewer:
  theme: 'generic'

# Add the calendar to the DateField
DateField:
  default_config:
    showcalendar: true


# Custom configuration for PHP Classes
SiteConfig:
  extensions:
    - BrandSiteConfigExtension
    - GoogleSiteConfigExtension

DataObject:
  extensions:
    - JsonSerializableDataExtension
    # - AdminModelExtension

Member:
  extensions:
    - MemberApiExtension
