---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---


# Custom configuration for PHP Classes
Page:
  extensions:
    - PageSidebarExtension

Page_Controller:
  extensions:
    - PageControllerSidebarExtension
