---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
  - 'surveys/*'
---


# Set the default theme
SSViewer:
  theme: 'generic'


# Custom configuration for PHP Classes
SiteConfig:
  extensions:
    - BrandSiteConfigExtension

DataObject:
  extensions:
    - JsonSerializableDataExtension

Member:
  extensions:
    - MemberApiExtension
