 # ...

variables:
    # MYSQL_DATABASE: ss_test_db
    # MYSQL_ROOT_PASSWORD: ss_test_db_password
    # MYSQL_USER: ss_test_db_user
    # MYSQL_PASSWORD: ss_test_db_password
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$VERSION_NUMBER
    DOCKER_DRIVER: overlay
    GITLAB_USER: gitlab-ci-token
    

before_script:
    - docker login -u $GITLAB_USER -p $CI_BUILD_TOKEN $CI_REGISTRY




stages:
    - test
    - deploy
    

testing:
    image: docker:latest
    stage: test
    script:
        - docker build --pull -t $CONTAINER_TEST_IMAGE .
        - docker run $CONTAINER_TEST_IMAGE bash scripts/test
        # - docker push $CONTAINER_TEST_IMAGE

coverage:
    image: docker:latest
    stage: test
    when: manual
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker run $CONTAINER_TEST_IMAGE bash scripts/coverage


deploy_image:
    image: docker:latest
    stage: deploy
    when: manual
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
