 # ...

run-automated-tests:
  image: mkpl/php-platform:base-2.6.1
  script:
    - cp -r /app/* .
    - mv _config/bootstrap.sh bootstrap.sh && mv _config/cronjobs cronjobs && mv _config/phpunit.xml phpunit.xml
    - bash scripts/test
