 # ...

variables:
    CONTAINER_BASE_IMAGE: $CI_REGISTRY_IMAGE:base
    CONTAINER_BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$VERSION_NUMBER
    DOCKER_DRIVER: overlay
    GITLAB_USER: gitlab-ci-token
    CI_PROJECT_DIR: '/app'
    

# before_script:
#     - docker login -u $GITLAB_USER -p $CI_BUILD_TOKEN $CI_REGISTRY




stages:
    - test
    - deploy
    

# build_base_image:
#     image: docker:latest
#     when: manual
#     stage: deploy
#     script:
#         - docker build -t $CONTAINER_BASE_IMAGE -f base.Dockerfile .
#         - docker push $CONTAINER_BASE_IMAGE

test:
    image: $CONTAINER_BASE_IMAGE
    stage: test
    script:
        - pwd
        - ls 
        - bash scripts/coverage
        # - docker run --rm $CONTAINER_BRANCH_IMAGE bash scripts/coverage
        # - docker push $CONTAINER_BRANCH_IMAGE


# publish_image:
#     image: docker:latest
#     when: manual
#     stage: deploy
#     script:
#         - docker pull $CONTAINER_BRANCH_IMAGE
#         - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#         - docker push $CONTAINER_RELEASE_IMAGE
