 # ...

variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:testing
    CONTAINER_BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$VERSION_NUMBER
    DOCKER_DRIVER: overlay
    GITLAB_USER: gitlab-ci-token
    

before_script:
    - docker login -u $GITLAB_USER -p $CI_BUILD_TOKEN $CI_REGISTRY




stages:
    - test
    

build_test_image:
    image: docker:latest
    when: manual
    script:
        - docker build --pull -t $CONTAINER_TEST_IMAGE .
        - docker push $CONTAINER_TEST_IMAGE

test:
    image: docker:latest
    stage: test
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker run $CONTAINER_TEST_IMAGE bash scripts/coverage
        # - docker push $CONTAINER_BRANCH_IMAGE


publish_image:
    image: docker:latest
    when: manual
    script:
        - docker pull $CONTAINER_BRANCH_IMAGE
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
