version: '2'

volumes:
  database_data:
    driver: local

services:
  web:
    container_name: mp_web
    build: .
    ports:
      - 8080:80
    links:
      - mysql
      - geo
    depends_on:
      - mysql
      - geo
    volumes:
      - ./mysite:/app/mysite
      - ./themes:/app/themes
      - ./assets:/app/assets
      - ./scripts:/app/scripts
      - ./surveys:/app/surveys
      - ./auth:/app/auth
      - ./maps:/app/maps
      - ./public:/app/public
      - ./interaction:/app/interaction
      - ./_config/phpunit.xml:/app/phpunit.xml:ro
    env_file:
      - secrets.env
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASS: secret
      DB_NAME: make-place
      SITE_ENV: dev
      DEFAULT_USER: admin
      DEFAULT_PASS: password
      GEO_URL: geo:3000
      GEO_KEY: 4DJ3Nws3h5zj73aKWUQIOavpVAVqeAaV
      PRIMARY_COL: '#836953'
    
  mysql:
    container_name: mp_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: make-place
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    
  geo:
    container_name: mp_geo
    image: 'openlab.ncl.ac.uk:4567/make-place/geo:1.1.1'
    ports:
      - 3000:3000
    expose:
      - 3000
    links:
      - mysql
    environment:
      SQL_URL: mysql://user:secret@mysql/make-geo
      NODE_ENV: dev
