version: '2'

volumes:
    database_data:
        driver: local

services:
    web:
        build: .
        ports:
            - 80
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - ./mysite:/app/mysite
            - ./themes:/app/themes
            - ./assets:/app/assets
        environment:
            DB_HOST: mysql
            DB_USER: user
            DB_PASS: password
            DB_NAME: ss-sample
            SITE_ENV: dev
            DEFAULT_USER: rob@veodesign.co.uk
            DEFAULT_PASS: password
    
    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: ss-sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
