---
Name: auth
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - AuthSiteConfigExtension
    - ConsentSiteConfigExtension

Member:
  extensions:
    - MemberOAuthExtension
    - MemberRegisterExtension
    - MemberProfileExtension
    - ConsentMemberExtension
