---
Name: auth
After:
  - 'framework/*'
  - 'cms/*'
---

SiteConfig:
  extensions:
    - AuthSiteConfigExtension

Member:
  extensions:
    - MemberOAuthExtension
    - MemberRegisterExtension
    - MemberProfileExtension
